### ISSUE TITLE
npm package contains .git file

### ISSUE THREAD

**Issue by efbenson** [koopjs/koop-logger#5]
It caused an issue with our build system and it pretty atypical of a node package.

![image](https://user-images.githubusercontent.com/976257/43212824-08b87aba-9003-11e8-9f10-3252815c1dac.png)

**Comment by rgwozdz** [comment]
Wow, that is odd. NPM is suppose exclude that [automatically](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).  I'll bump the version and see if it happens again.

**Comment by rgwozdz** [comment]
Nope, its still there....

**Comment by rgwozdz** [comment]
Fixed in v2.0.4.

**Comment by jgravois** [comment]
I've become very fond of [`npm pack`](https://docs.npmjs.com/cli/pack) for things like this.
